language: clojure
lein: lein2
sudo: required
services:
  - docker
before_install:
  - docker pull postgres:10
  - docker run --name pg10 -p 5555:5432 -e POSTGRES_PASSWORD=pass -d postgres:10
jdk:
  - oraclejdk8
script: lein test
